### ISSUE TITLE
The font going wrong on HyperOS

### ISSUE THREAD

**Issue by avisadius** [tharunbirla/FetchIt#11]
![Screenshot_2024-10-22-02-02-09-211_com tharunbirla fetchit](https://github.com/user-attachments/assets/50e9e64e-05e2-464e-99e9-8732ad1f6ce6)
Hi devs, thankyou for mking such a grateful app, but the font going wromg, i can't see anything (well I can see just a bit) and I've laready use dark mode

Info:

DensityDpi: 345
Density: 2.15625
scaledDensity: 1.7465625
dpis: 409.432 x 409.127
pixels: 1080 x 2307
current size: 1080 x 632
Android: 13
Model: 2201117TY
Manufacturer: Xiaomi

**Comment by tharunbirla** [comment]
Hi @avisadius,

Thanks for your report! The font issue you're experiencing in dark mode is due to improper theming of the app. Will be fixing this in the next release.

**Comment by avisadius** [comment]
thankyou devs!
