### ISSUE TITLE
Feature: Download Progress

### ISSUE THREAD

**Issue by Quantum-Future** [tharunbirla/FetchIt#13]
Good app !
When download starts, you don't get any feedback to know if the download is advancing and how much remains.
You get a notification once the download has finished or failed, but nothing in between (from start to end).
Can you add a download progress bar with % of completion?

**Comment by tharunbirla** [comment]
@Quantum-Future thanks for your feedback, glad you liked the app.

I was planning of adding a notification progress bar since I got lot of suggestions for this. I will work for this in upcoming updates. 🙂

Thanks for your suggestion!

**Comment by tharunbirla** [comment]
Hi @Quantum-Future ,
Fixed this issue in d481175ff5dbcf96fe5edea87a00c50df14bcfef
Check out [v1.4](https://github.com/tharunbirla/FetchIt/releases/tag/v1.4)

**Comment by Quantum-Future** [comment]
Ok, I'll check it when it's available on F-Droid.
Thanks !

**Comment by Quantum-Future** [comment]
I checked Ver 1.4 and the first time I didn't notice any change.
I tried againg and I discovered that the download progress is hidden: I have to swipe down from top of screen to see download status.  (My phone has Android 9).
Maybe it's better to show the download bar in the app's screen.

**Comment by tharunbirla** [comment]
I'm considering updating the app's user interface and may include progress indication or download progress display. 
The app lacks theming and other UI enhancements are needed anyway.

**Comment by Quantum-Future** [comment]
Yes, black background would be good too.
