### ISSUE TITLE
downloaded video not playing

### ISSUE THREAD

**Issue by rajarshikhatua** [tharunbirla/FetchIt#15]
i downloaded the video but the video file is not playing in my phone , i downloaded this video https://www.instagram.com/p/DBTweE4zF2d/?igsh=OWM1aWdsbGVzOWI1

**Comment by tharunbirla** [comment]
The link you provided leads to an image post, not a video. Please double-check the link to ensure it's for a video, or if you're referring to a different content type, let me know.

**Comment by rajarshikhatua** [comment]
yes but the image also not downloading , try for yourself

**Comment by tharunbirla** [comment]
FetchIt is for downloading videos. Please try a video link.
