### ISSUE TITLE
Can't Download video from Youtube

### ISSUE THREAD

**Issue by karthi-rt** [tharunbirla/FetchIt#16]
Copy & Paste the youtube url in the textbox then click the download button, video is not downloaded

**Comment by leminsc8er** [comment]
Same. 

Example https://youtu.be/_bWjmkmxS3M


Codes frm Projects like http://NewPipe.net, http://jdownloader.org PR http://sharedownloader.net can be helpfull. Lason works in past!

**Comment by karthi-rt** [comment]
> Same.
> 
> Example https://youtu.be/_bWjmkmxS3M
> 
> Codes frm Projects like http://NewPipe.net, http://jdownloader.org PR http://sharedownloader.net can be helpfull. Lason works in past!
Thanks

**Comment by tharunbirla** [comment]
@rt-karthi Thanks for noticing this issue 
I will work on this and update soon.

@leminsc8er sure I will have a look into those projects as well.

**Comment by rt-karthi** [comment]
You're welcome! Take your time, and please let me know if you need any assistance. I look forward to your update.

**Comment by karthi-rt** [comment]
You're welcome! Take your time, and please let me know if you need any assistance. I look forward to your update.

**Comment by tharunbirla** [comment]
Cobalt API is officially shutdown
https://github.com/imputnet/cobalt/discussions/860
