### ISSUE TITLE
App Crashing

### ISSUE THREAD

**Issue by Eliya-Manoj** [tharunbirla/FetchIt#2]
After installed Fetchit, It cannot open. ( Crashing )

Samsung M31
Android 12

**Comment by hinddhiwar** [comment]
Same
Redmi 8 
Android 10

**Comment by tharunbirla** [comment]
Thanks for reporting the issue, @Eliya-Manoj  and @hinddhiwar ! This might be related to permission handling. I'm currently working on the problem and will fix it. Thank you for your patience!
