### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by RahulxPaul** [tharunbirla/FetchIt#3]
Android 12 
Moto G51 5G

**Comment by tz-shuhag** [comment]
Same issue app crashes

Android 11

**Comment by tharunbirla** [comment]
Thanks for your comments, @RahulxPaul  and @tz-shuhag ! The crashes may be related to how permissions are handled on Android 11 and 12. I’m looking into it and will work on a fix. Your patience is appreciated!

**Comment by tharunbirla** [comment]
Since both issues (#2 and #3) are related to app crashes on launch, I will be merging them for better tracking. Please refer to issue #2 for updates. Thank you for your patience as I work on a fix!
