### ISSUE TITLE
Won't download from Facebook reels

### ISSUE THREAD

**Issue by Nkumbza** [tharunbirla/FetchIt#4]
I use the share button on the Facebook reel to get the url, the paste it to this app.
The error is "failed to get video URL" on the notification. 
I'm using lineageOS 21 Android 14.

![Screenshot_20241011-092256_Chrome](https://github.com/user-attachments/assets/1ed2f1b7-5110-4e06-853a-0b0aef25930a)

**Comment by tharunbirla** [comment]
Hi @Nkumbza. Thanks for reporting this issue. There’s an issue with fetching video URLs from Facebook Reels in the current code. I’ll work on a fix soon. Thanks for your patience!

**Comment by whatistime** [comment]
Same issue here

**Comment by tharunbirla** [comment]
@whatistime and @Nkumbza, a new commit has been made to fix this issue a1905d37c64c3e9f3c78585299153ecc14536c31. 
It will be included in the upcoming version **v1.2**, along with UI updates.
