### ISSUE TITLE
Add support for TikTok

### ISSUE THREAD

**Issue by psydex** [tharunbirla/FetchIt#5]
Add support for Tiktok and this app would become #1 recommended!

**Comment by tharunbirla** [comment]
Hi @psydex the app already supports TikTok, and you can download videos directly from it.

**Supported Platforms:**

* YouTube
* Facebook
* Instagram
* Twitter
* TikTok
* Reddit
* Vimeo
* Dailymotion
* Pinterest
* Snapchat
* SoundCloud
* Twitch
* Tumblr
* Bilibili
* Loom
* Streamable
* VK
* Rutube
* Bluesky
* Vine
* OK

P.S. There’s currently an issue with downloading Facebook content, and working on a fix.

**Comment by psydex** [comment]
Tiktok support is great but can you add option to share link directly from the Android's share menu instead of copying and pasting the video link manually?
