### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [tharunbirla/FetchIt#8]
https://gitlab.com/fdroid/fdroiddata/-/jobs/8098459686#L584

can you please build the app for release FROM the git tree and from the exact tagged commit? And not from a tarball.

**Comment by tharunbirla** [comment]
@licaon-kter both v1.1 and v1.2?

**Comment by licaon-kter** [comment]
latest 1.2

**Comment by tharunbirla** [comment]
@licaon-kter All done! 👍 Please confirm.

**Comment by licaon-kter** [comment]
https://gitlab.com/fdroid/fdroiddata/-/jobs/8100193573#L584 nope... built from a folder that has no `.git` still

**Comment by tharunbirla** [comment]
Will look into it.
